[package]
name = "bmb-rand"
version = "0.1.0"
description = "Pseudo-random number generation for BMB"
authors = ["BMB Team"]
license = "MIT"
repository = "https://github.com/lang-bmb/gotgan-packages"

[dependencies]
