[package]
name = "bmb-regex"
version = "0.1.0"
description = "Regular expression matching for BMB"
authors = ["BMB Team"]
license = "MIT"
repository = "https://github.com/lang-bmb/gotgan-packages"

[dependencies]
