[package]
name = "bmb-collections"
version = "0.1.0"
description = "Collection data structures for BMB: HashMap, VecDeque, BTreeMap"
authors = ["BMB Team"]
license = "MIT"
repository = "https://github.com/lang-bmb/gotgan-packages"

[dependencies]
