[package]
name = "bmb-testing"
version = "0.1.0"
description = "Testing framework for BMB programs"
authors = ["BMB Team"]
license = "MIT"
repository = "https://github.com/lang-bmb/gotgan-packages"

[dependencies]
